[providers.docker]
endpoint = "unix:///var/run/docker.sock"
exposedByDefault = false

[serversTransport]
insecureSkipVerify = true

[entryPoints]
[entryPoints.web]
address = ":7890"

[entryPoints.traefik]
address = ":9090"

[api]
dashboard = true
debug = true

[log]
level = "DEBUG"
filePath = "/var/log/traefik/DEBUG.log"

[accessLog]
filePath = "/var/log/traefik/access.log"
